[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt && python -m spacy download en_core_web_sm"

[deploy]
startCommand = "python app.py"
healthcheckPath = "/"
healthcheckTimeout = 100